sudo: required
services:
  - docker
install:
  - docker build -t niggusch/java-mvn-mongo .
  - docker run -d -p 127.0.0.1:27017:27017 --name java-mvn-mongo niggusch/java-mvn-mongo
  - docker ps -a

script:
  - docker ps | grep -q java-mvn-mongo

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.docker.com;
    docker push $DOCKER_USERNAME/java-mvn-mongo;
    fi

# see https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
